In [26]:
include("../src/variationaltimedisc.jl")

Main.VariationalTimeDisc

In [27]:
TD = Main.VariationalTimeDisc.SetVariationalTimeDisc(Float64, 3, 0)


VariationalTimeDisc(r=3, k=0): dG(3)
[1.0]
[1.0, 1.0]
[1.0, 2.0, 1.0]
[1.0, 3.0, 3.0, 1.0]


Main.VariationalTimeDisc.TimeDiscretization{Float64, Int64}(0, 1, [4, 3, 7, 3, 7, 3], [5, 4, 7, 7, 7, 7], [-0.822824080974592, -0.18106627111853058, 0.5753189235216941, 1.0], [2.8220539379750433 0.9617536385273553 -0.2929507410519059 0.08693917628712211; -2.524607319195704 0.6105500144473458 0.8773404943804168 -0.21739573060629136; 1.7462330793127225 -1.9922589478912525 0.31739604757761025 0.9110687992171282; -3.4617441282227315 3.2976188348140774 -6.085874706591354 4.250000000000003], [1.0 5.422151903470221e-17 -1.3882120022291487e-18 -6.317718427493545e-17; 2.121099725378962e-16 0.9999999999999998 7.933923299889335e-17 -1.1827462211602778e-16; -4.869002122703291e-17 1.253788730014483e-16 1.0 2.80773576020615e-16; -2.3235640609564235e-16 -8.764780421582707e-16 -4.522927713055005e-16 0.9999999999999999], 7, [-0.9491079123427585, -0.7415311855993945, -0.4058451513773972, -6.162975822039155e-33, 0.4058451513773972, 0.7415311855993945, 0.9491079123427585, 1.0], [0.1294849661688693, 0.2797

In [21]:
A=[-3.447796669508086 -2.4501952901047424 -1.171408851039996 -0.17735889242798492 0.21245803880491787 0.07830714994090929 -0.2114908757261627 -0.3066688486743354; 5.94779799656508 3.5665100720290632 0.6698525225031735 -1.2574230254707714 -1.460911875771034 -0.32666998721963875 0.9648005580673162 1.3502656444120276; -4.097231786533192 -1.7566353084788444 0.8103305290738525 1.9035319178987566 0.7962683786705267 -1.7823286622746584 -4.130117477460024 -4.793596795737693; 1.5972304594761983 0.6403205265545234 -0.30877420053703 -0.4687500000000001 0.45218545829558976 2.030691499553388 3.3768077951188706 3.750000000000001]
B=[-3.4478  -2.4502 -1.17141 -0.177359 0.212458 0.0783071 -0.211491 -0.306669; 
  5.9478  3.56651 0.669853 -1.25742 -1.46091 -0.32667 0.964801  1.35027 ;
-4.09723 -1.75664 0.810331  1.90353 0.796268 -1.78233 -4.13012  -4.7936 ;
 1.59723 0.640321 -0.308774 -0.46875 0.452185  2.03069  3.37681     3.75]
A-B

4×8 Matrix{Float64}:
  3.33049e-6   4.7099e-6    1.14896e-6  …   1.24274e-7   1.51326e-7
 -2.00343e-6   7.20291e-8  -4.77497e-7     -4.41933e-7  -4.35559e-6
 -1.78653e-6   4.69152e-6  -4.70926e-7      2.52254e-6   3.20426e-6
  4.59476e-7  -4.73445e-7  -2.00537e-7     -2.20488e-6   8.88178e-16

In [24]:
[1.6123724356957938 0.5839200423452027 -0.12659863237109015; -1.783920042345202 0.3876275643042052 0.5265986323710905; 2.765986323710904 -3.7659863237109037 2.4999999999999996]

3×3 Matrix{Float64}:
  1.61237   0.58392   -0.126599
 -1.78392   0.387628   0.526599
  2.76599  -3.76599    2.5

In [57]:
C=[-0.17735889242798492 1.704919826130989 -1.8342297823773395 0.0; -1.2574230254707714 -2.62509529933105 5.232783969213849 0.0; 1.9035319178987566 -0.017324526799938678 -6.679804186836511 0.0; -0.4687500000000001 0.9375 3.281250000000001 0.0]

4×4 Matrix{Float64}:
 -0.177359   1.70492    -1.83423  0.0
 -1.25742   -2.6251      5.23278  0.0
  1.90353   -0.0173245  -6.6798   0.0
 -0.46875    0.9375      3.28125  0.0

In [23]:
N=zeros(10)
N[1:2:5]= 2.//5
println(N)

LoadError: syntax: invalid syntax "2./"; add space(s) to clarify

In [35]:
A=[1.0 1.0 1.0 1.0 1.0; -0.8857916077709647 -0.4463139727237524 0.16718086473783364 0.7204802713124389 1.0; 0.7846267723974705 0.1991961622484584 0.027949441534489826 0.5190918213504455 1.0; -0.6950158102220981 -0.08890403052443462 0.004672611804675533 0.37399541628263705 1.0; 0.6156391719628719 0.03967911105451417 0.000781171282089865 0.2694563189929228 1.0]

5×5 Matrix{Float64}:
  1.0        1.0        1.0          1.0       1.0
 -0.885792  -0.446314   0.167181     0.72048   1.0
  0.784627   0.199196   0.0279494    0.519092  1.0
 -0.695016  -0.088904   0.00467261   0.373995  1.0
  0.615639   0.0396791  0.000781171  0.269456  1.0

In [4]:
B=[1 1 1 1 1 ;
-0.885791607770964 -0.446313972723752 0.167180864737833 0.720480271312439 1 ;
0.78462677239747 0.199196162248458 0.0279494415344898 0.519091821350446 1 ;
-0.695015810222098 -0.0889040305244345 0.00467261180467551 0.373995416282637 1 ;
0.615639171962871 0.0396791110545141 0.000781171282089861 0.269456318992923 1 ]

5×5 Matrix{Float64}:
  1.0        1.0        1.0          1.0       1.0
 -0.885792  -0.446314   0.167181     0.72048   1.0
  0.784627   0.199196   0.0279494    0.519092  1.0
 -0.695016  -0.088904   0.00467261   0.373995  1.0
  0.615639   0.0396791  0.000781171  0.269456  1.0

In [5]:
inv(B)

5×5 Matrix{Float64}:
 -0.0383515   0.235054   0.118155  -1.02826    0.713401
  0.234496   -1.69789    1.45928    2.20195   -2.19784
  0.956875    0.939217  -3.95078   -1.3047     3.3594
 -0.22802     0.823616   3.42335   -0.568984  -3.44996
  0.075      -0.3       -1.05       0.7        1.575

In [42]:
using LinearAlgebra

In [46]:
B

5×5 Matrix{Float64}:
  1.0        1.0        1.0          1.0       1.0
 -0.885792  -0.446314   0.167181     0.72048   1.0
  0.784627   0.199196   0.0279494    0.519092  1.0
 -0.695016  -0.088904   0.00467261   0.373995  1.0
  0.615639   0.0396791  0.000781171  0.269456  1.0

In [2]:
t=[1 2 3; 4 5 6; 7 8 8]

3×3 Matrix{Int64}:
 1  2  3
 4  5  6
 7  8  8

In [3]:
inv(t)

3×3 Matrix{Float64}:
 -2.66667   2.66667  -1.0
  3.33333  -4.33333   2.0
 -1.0       2.0      -1.0